apiVersion: apps/v1
kind: Deployment
metadata:
  name: precedentia-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: docker.io/gabguimaraes/precedentia-api:latest
        

        env:
          - name: DATABASE_URL
            value: "postgresql+psycopg2://admin:admin@postgres-service:5432/precedentia-users"
          - name: EMBEDDING_URL
            value: "http://embedding-service:5001"
          - name: SUMMARY_URL
            value: "http://summary-service:5002"

        ports:
        - containerPort: 5000
        # ... resto das configurações ...
