"""Adiciona file_path no modelo da peticao

Revision ID: e97ce5dcecc0
Revises: efc482bc5e98
Create Date: 2026-05-12 09:28:26.302650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97ce5dcecc0'
down_revision: Union[str, Sequence[str], None] = 'efc482bc5e98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petitions', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('petitions', 'file_path')
    # ### end Alembic commands ###
