#!/usr/bin/env sh

echo
echo "🔍 Running lint (ruff)..."
ruff check .
if [ $? -ne 0 ]; then
	echo "❌ Lint failed. Commit aborted."
	exit 1
fi

echo
echo "🎨 Checking code formatting..."
black --check .
if [ $? -ne 0 ]; then
	echo "❌ Code is not formatted. Run 'black .'"
	exit 1
fi

echo
echo "✅ All checks passed!"